### PR TITLE
Change #[pinned_drop] to trait implementation

### LINKED ISSUE #26: Weirdly different approach to `Unpin` vs `Drop`
Looking at these two examples
```rust
use std::fmt::Debug;
use pin_project::pin_project;
use std::pin::Pin;

pin_project! {
    #[pin_projectable]
    pub struct Foo<T: Debug, U: Debug> {
        #[pin] pinned_field: T,
        unpin_field: U
    }

    #[pinned_drop]
    fn my_drop_fn<T: Debug, U: Debug>(foo: Pin<&mut Foo<T, U>>) {
        let foo = foo.project();
        println!("Dropping pinned field: {:?}", foo.pinned_field);
        println!("Dropping unpin field: {:?}", foo.unpin_field);
    }
}

fn main() {
    Foo { pinned_field: true, unpin_field: 40 };
}
```

```rust
use pin_project::{pin_projectable, UnsafeUnpin};
use std::pin::Pin;

#[pin_projectable(unsafe_Unpin)]
struct Foo<T, U> {
    #[pin]
    future: T,
    field: U,
}

impl<T, U> Foo<T, U> {
    fn baz(self: Pin<&mut Self>) {
        let this = self.project();
        let _: Pin<&mut T> = this.future; // Pinned reference to the field
        let _: &mut U = this.field; // Normal reference to the field
    }
}

unsafe impl<T: Unpin, U> UnsafeUnpin for Foo<T, U> {} // Conditional Unpin impl
```

it is odd that for a very similar situation (let the user "hook" into the auto-generated trait impl), this crate uses two totally different approaches: one time it is an attribute at the type, and one time it is a block *around* the entire thing *plus* an attribute at the `impl`.

To make the crate easier to use, it would be much better if the same approach could be used both times.

### PR DESCRIPTION
**Pull request by taiki-e**
proc-macro just rewrites the trait path and adds `unsafe`.
It needs to write the documentation more.

### Examples
Before:
```rust
use pin_project::{pin_project, pinned_drop, UnsafeUnpin};
use std::pin::Pin;

#[pin_project(UnsafeUnpin, PinnedDrop)]
pub struct Foo<T, U> {
    #[pin] pinned_field: T,
    unpin_field: U
}

#[pinned_drop]
fn do_drop<T, U>(this: Pin<&mut Foo<T, U>>) {
    // ..
}

unsafe impl<T: Unpin, U> UnsafeUnpin for Foo<T, U> {}
```

After:

```rust
use pin_project::{pin_project, pinned_drop};
use std::pin::Pin;

#[pin_project(UnsafeUnpin, PinnedDrop)]
pub struct Foo<T, U> {
    #[pin] pinned_field: T,
    unpin_field: U
}

#[pinned_drop]
impl<T, U> PinnedDrop for Foo<T, U> {
    fn drop(self: Pin<&mut Self>) {
        // ..
    }
}

unsafe impl<T: Unpin, U> UnsafeUnpin for Foo<T, U> {}
```

Closes #26

### CODE REVIEW

**Comment by taiki-e** [comment]
We also need to decide the method name: `drop` vs `pinned_drop`
```rust
#[pinned_drop]
impl<T, U> PinnedDrop for Foo<T, U> {
    fn pinned_drop(self: Pin<&mut Self>) {}
}
// vs
#[pinned_drop]
impl<T, U> PinnedDrop for Foo<T, U> {
    fn drop(self: Pin<&mut Self>) {}
}
```

**Comment by RalfJung** [comment]
> proc-macro just rewrites the trait path and adds `unsafe`.

Why does it have to add unsafe?
I am somewhat surprised that the `pinned_drop` macro is needed at all.

**Comment by taiki-e** [comment]
@RalfJung 

> Why does it have to add unsafe? And why is it safe to do so?
> I am somewhat surprised that the `pinned_drop` macro is needed at all.


It is safe to implement `PinnedDrop::drop`, but it is not safe to call it. This is because destructors can be called multiple times (double dropping is unsound: https://github.com/rust-lang/rust/pull/62360).

Ideally, it would be desirable to be able to prohibit manual calls in the same way as `Drop::drop`, but the library cannot. So, by using macros and replacing them with private unsafe traits, we prevent users from calling `PinnedDrop::drop`.

**Comment by RalfJung** [comment]
Thanks, that explanation should be in the code somewhere.

One thing though: if it is safe to implement, why is the trait unsafe? It should not be. Only its method should be unsafe, reflecting that it is unsafe to call.

**Comment by taiki-e** [comment]
> that explanation should be in the code somewhere.

Although it is in a place that was not changed by this PR, I think this should be explained in the document, so I filed #88.

> One thing though: if it is safe to implement, why is the trait unsafe? It should not be. Only its method should be unsafe, reflecting that it is unsafe to call.

Indeed. I forgot to update it.

**Pull request merged**
